######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 4 13:07:38 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += testlib
# Input
HEADERS += testnullfxp.h
SOURCES += testmain.cpp testnullfxp.cpp
